services:
  db:
    image: mysql:8.0
    container_name: mysql_esport
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ghiervis
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: esport
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
